steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke/bank-web-gke',
        '--build-arg',
        'REACT_APP_API_URL=http://35.224.132.174/api/v1',
        '.'
      ]
images:
  - 'us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke/bank-web-gke'
