# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       [
#         'build',
#         '-t',
#         'us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke-test/bank-web-gke',
#         '--build-arg',
#         'REACT_APP_API_URL=http://35.224.132.174/api/v1',
#         '.'
#       ]
# images:
#   - 'us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke-test/bank-web-gke'








# cloudbuild-frontend.yaml
steps:
  # Backend URL'sini al
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe bank-backend --region=northamerica-northeast2 --format="value(status.url)")
        echo "Backend URL: $BACKEND_URL"
        echo $BACKEND_URL > /workspace/backend-url.txt
    id: Get Backend URL
  
  # Frontend'i build et
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend-url.txt)
        docker build \
          --build-arg REACT_APP_API_URL=$BACKEND_URL \
          -t northamerica-northeast1-docker.pkg.dev/molten-unison-462818-r2/app-repo/bank-frontend:$COMMIT_SHA \
          -f frontend/Dockerfile \
          ./frontend
    id: Build Frontend Container Image
  
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'northamerica-northeast1-docker.pkg.dev/molten-unison-462818-r2/app-repo/bank-frontend:$COMMIT_SHA'
    id: Push Frontend Image to Artifact Registry
  
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - bank-frontend
      - '--image'
      - 'northamerica-northeast1-docker.pkg.dev/molten-unison-462818-r2/app-repo/bank-frontend:$COMMIT_SHA'
      - '--region'
      - northamerica-northeast1
      - '--platform'
      - managed
      - '--port'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PORT=80'
    id: Deploy Frontend to Cloud Run
images:
  - 'northamerica-northeast1-docker.pkg.dev/molten-unison-462818-r2/app-repo/bank-frontend:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s