apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-web
  template:
    metadata:
      labels:
        app: bank-web
    spec:
      containers:
      - name: bank-web
        #image: gcr.io/molten-unison-462818-r2/bank-web-gke
        image: us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke-test/bank-web-gke
        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bank-web-service
spec:
  selector:
    app: bank-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80   
  type: LoadBalancer
